{
    "version": 1.0,
    "input_error": "\u001b[91mFout:\u001b[0m Ik weet niet zeker wat je daar mee bedoelt!",
    "back_to_menu": "Druk op [ENTER] om terug te gaan naar het hoofdmenu",
    "cancel": "Annuleer",
    "intro_1": "Welkom in \u001b[1mPyPlace\u001b[0m!",
    "intro_2": "PyPlace is een Python applicatie die er voor zorgt",
    "intro_3": "dat je een simpel overzicht krijgt van je andere Python",
    "intro_4": "applicaties, en het zorgt er voor dat je gemakkelijk",
    "intro_5": "nieuwe kan installeren!",
    "replit_warning": "\u001b[93mWAARSCHUWING\u001b[0m Het lijkt er op dat je dit uitvoert via de Replit pagina! Sommige dingen zullen misschien niet goed werken door de andere namen van de bestanden. We raden je aan om PyPlace te downloaden en het zelf uit te voeren.",
    "file_name_warning": "\u001b[93mWAARSCHUWING:\u001b[0m Het lijkt er op dat je dit vanaf een bestand uitvoert dat niet \"pyplace.py\" is genaamd. \nDit betekent dat je niet PyPlace kunt herstellen of updaten. We raden je aan om het \"pyplace.py\" te noemen.",
    "setup_1": "Wat commando gebruik je om een Python bestand uit te voeren in je terminal?",
    "setup_2": "Laat het leeg om het te zetten op de standaard. (python3)",
    "setup_3": "\u001b[1mLet op:\u001b[0m Je kan dit later veranderen in de instellingen",
    "setup_4": "\u001b[94mPyPlace wordt ingesteld...\u001b[0m",
    "setup_5": "\u001b[92mPyPlace is ingesteld!\u001b[0m",
    "setup_6": "Druk op [ENTER] om PyPlace op te starten",
    "main_menu_option_1": "Open een PyPlace app",
    "main_menu_option_2": "Download een PyPlace app",
    "main_menu_option_3": "Open instellingen",
    "main_menu_option_4": "Sluit PyPlace",
    "main_menu_message_1": "Wat wil je graag doen?",
    "main_menu_message_2": "Voer het nummer of de letter in voor wat je graag wilt doen:",
    "update_error_1": "\u001b[91mFout:\u001b[0m Kon niet niet voor updates zoeken! Antwoord code: [code]",
    "update_error_2": "\u001b[91mFout:\u001b[0m Kon niet het PyPlace bestand krijgen! Antwoord code: [code]",
    "update_warning_1": "\u001b[93mWAARSCHUWING:\u001b[0m Je huidige versie lijkt nieuwer te zijn dan de laatste versie die is gepubliceerd!",
    "update_message_1": "\u001b[1mUPDATE BESCHIKBAAR!\u001b[0m",
    "update_message_2": "Je huidige versie ([version]) is niet langer de laateste versie! De laatste versie is [version_latest].",
    "update_message_3": "Hier zijn de veranderingen:",
    "update_message_4": "Wil je nu updaten?",
    "update_message_5": "\u001b[94mLaatste versie van PyPlace aan het downloaden...\u001b[0m",
    "update_message_6": "\u001b[92mDe laatste versie van PyPlace is nu beschikbaar in \u001b[1mPyPlace.py!\u001b[0m",
    "update_message_7": "Wil je het nu uitvoeren?",
    "update_message_8": "\u001b[94mProberen om PyPlace.py uit te voeren...\u001b[0m",
    "update_message_9": "Doorgaan met huidige versie. \u001b[1mLet op:\u001b[0m De volgende keer dat je PyPlace.py start, zal het op de laatste versie zijn!",
    "execute_file_error_1": "\u001b[91mFout:\u001b[0m Het lijkt er op dat je geen apps hebt ge\u00efnstalleerd! Je kan ze downloaden via \"Download een PyPlace app\" in het hoofdmenu.",
    "execute_file_error_2": "\u001b[91mFout:\u001b[0m Dit is geen Python bestand, en kan dus niet uitgevoerd worden door PyPlace.",
    "execute_file_message_1": "\u001b[93m\u25a0\u001b[0m: Experimentele applicatie",
    "execute_file_message_2": "\u001b[96m\u25a0\u001b[0m: Applicatie gedownload van de PyPlace Store",
    "execute_file_message_3": "Welk nummer app wil je openen?",
    "execute_file_message_4": "\u001b[94mProberen om [app] uit te voeren...\u001b[0m",
    "execute_file_message_5": "\u001b[92mBestand uitgevoerd\u001b[0m",
    "download_file_error_1": "\u001b[91mFout:\u001b[0m Dit is niet een Python bestand, en kan daarom niet gedownload worden door PyPlace",
    "download_file_error_2": "\u001b[91mFout:\u001b[0m Kon het Python bestand niet downloaden! Status code: [code]",
    "download_file_error_3": "\u001b[91mFout:\u001b[0m Een bestand met die naam ([name]) bestaat al!",
    "download_file_error_4": "\u001b[91mError:\u001b[0m Dat lijkt niet op een geldige URL!",
    "download_file_option_1": "URL naar Python bestand",
    "download_file_option_2": "Download van de PyPlace Store",
    "download_file_option_3": "Download experiment",
    "download_file_option_4": "Voeg lokaal bestand toe",
    "download_file_message_1": "Hoe wil je een PyPlace app toevoegen?",
    "download_file_message_2": "Vul de directe URL in naar het Python bestand:",
    "download_file_message_3": "\u001b[94mPython app aan het downloaden...\u001b[0m",
    "download_file_message_4": "\u001b[92mPython app gedownload!\u001b[0m",
    "download_file_message_5": "Hoe wil je dit bestand noemen?",
    "download_file_message_6": "Hoe wil deze app noemen?",
    "download_file_message_7": "\u001b[94mPython app aan het installeren...\u001b[0m",
    "download_file_message_8": "\u001b[92mPython app ge\u00efnstalleerd!\u001b[0m",
    "download_file_message_9": "Het kan nu geopend worden via de \"Open een PyPlace app\" functie in het hoofdmenu!",
    "download_file_message_10": "Welk nummer app wil je downloaden?",
    "download_file_message_11": "Wat is de naam van het bestand dat je graag wilt toevoegen? \u001b[1mLet op:\u001b[0m Dit \u001b[4mMOET\u001b[0m in je huidige folder zijn.",
    "settings_error_1": "\u001b[91mFout:\u001b[0m Dit is niet beschikbaar wanneer PyPlace wordt uitgevoerd op Replit. \u001b[1mJe kan in plaats daarvan PyPlace downloaden.\u001b[0m",
    "settings_option_1": "Verwijder een app",
    "settings_option_2": "Verander het Python commando",
    "settings_option_3": "Herstel naar de laatste versie",
    "settings_option_4": "Over",
    "settings_option_5": "Terug naar het hoofdmenu",
    "settings_message_1": "Vul het nummer of de letter in voor wat je wilt doen.",
    "settings_message_2": "Welke apps wil je verwijderen? (gescheiden door een spatie, dus voor apps 1, 2 en 3, zou je 1 2 3 invullen.)",
    "settings_message_3": "Wat wil je graag dat het nieuwe commando is? Laat leeg om het naar de standaar te zetten (python3).",
    "settings_message_4": "Commando ge\u00fcpdate naar [command]!",
    "settings_message_5": "Weet je zeker dat je wilt herstellen naar de laatste gepubliceerde versie?",
    "settings_message_6": "\u001b[94mLaatste versie van PyPlace wordt gedownload...\u001b[0m",
    "settings_message_7": "\u001b[92mDe laatste versie van PyPlace is nu beschikbaar in \u001b[1mPyPlace.py!\u001b[0m",
    "settings_message_8": "Wil je het uitvoeren?",
    "settings_message_9": "\u001b[94mProberen om PyPlace.py uit te voeren...\u001b[0m",
    "settings_message_10": "Doorgaan met huidige versie. \u001b[1mLet op:\u001b[0m De volgende keer dat je PyPlace.py start, zal het op de laatste versie zijn!",
    "bulk_delete_message_1": "\u001b[94mGeen apps om te verwijderen\u001b[0m",
    "bulk_delete_message_2": "\u001b[92m[amount] app(s) verwijderd!\u001b[0m"
}
